global:
  scrape_interval: 5s 
  evaluation_interval: 5s
  scrape_timeout: 4s  # evaluation interval보다 크면 안됨


scrape_configs:
  - job_name: 'server-1'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['192.168.1.12:8081']
